redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/regevazriel/dev/private/winnow/packages/landing"
publishOrigin = "config"
base = "/Users/regevazriel/dev/private/winnow/packages/landing"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/packages/landing/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/index.html"
to = "/packages/landing/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/styles.css"
to = "/packages/landing/styles.css"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]